-- AlterTable
ALTER TABLE `batchimport` MODIFY `status` ENUM('DRAFT', 'QUEUED', 'PENDING', 'PROCESSING', 'COMPLETED', 'FAILED') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `batchimportitem` MODIFY `status` ENUM('DRAFT', 'QUEUED', 'PENDING', 'PROCESSING', 'COMPLETED', 'FAILED') NOT NULL DEFAULT 'PENDING';
